image: cm0x4d/ubuntu-qt5-cmake

build:
    script:
        # Get dependencies
        - apt-get --yes update
        - apt-get --yes install pkg-config libssh-dev wget
        - wget https://www.libssh.org/files/0.9/libssh-0.9.2.tar.xz
        - tar xf libssh-0.9.2.tar.xz
        - cd libssh-0.9.2
        - mkdir build
        - cd build
        - cmake ..
        - make install
        - cd ../..
        
        # Actually build and install QJournalctl
        - ./autogen.sh
        - make
        - ls -lh qjournalctl

packaging_deb:
    script:
        - apt-get --yes update
        - apt-get install curl make
        - curl -fsSL https://get.docker.com -o get-docker.sh
        - sh get-docker.sh
        - cd packaging/deb/
        - make

packaging_snap:
    script:
        - apt-get --yes update
        - apt-get install curl make
        - curl -fsSL https://get.docker.com -o get-docker.sh
        - sh get-docker.sh
        - cd packging/snap/
        - make
