image: cm0x4d/ubuntu-qt5-cmake
stages:
    - build

build:
    stage: build
    script:
        - apt-get --yes update
        - apt-get --yes install pkg-config libssh-dev
        - ./autogen.sh
        - make
        - ls -lh qjournalctl
