language: cpp

services:
  - docker

before_script:
  - docker pull cm0x4d/ubuntu-qt5-cmake

script:
  - docker run -it -v"$(pwd):/build" --security-opt seccomp:unconfined cm0x4d/ubuntu-qt5-cmake sh -c "apt-get --yes update && apt-get --yes install pkg-config libssl-dev zlib1g-dev pkg-config wget && wget https://www.libssh.org/files/0.9/libssh-0.9.5.tar.xz && tar xf libssh-0.9.5.tar.xz && cd libssh-0.9.5 && mkdir build && cd build && cmake .. && make install && cd /build && ./autogen.sh && make ; ls -lh qjournalctl"

